# Generated by Django 5.0.1 on 2024-02-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0003_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='approval',
            field=models.BooleanField(default=False),
        ),
    ]
