# Generated by Django 5.0.1 on 2024-02-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0004_staff_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=100, null=True)),
                ('room_type', models.CharField(max_length=100, null=True)),
                ('room_price', models.IntegerField(null=True)),
                ('availability', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
