# Generated by Django 5.0.1 on 2024-02-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0006_delete_admin_remove_room_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='availabilty',
            field=models.BooleanField(default=False),
        ),
    ]
