# Generated by Django 5.0.1 on 2024-02-08 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0008_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='availabilty',
            new_name='availability',
        ),
    ]
