# Generated by Django 5.0.1 on 2024-02-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0009_rename_availabilty_room_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='approval',
            field=models.BooleanField(default=False),
        ),
    ]
