# Generated by Django 5.0.1 on 2024-02-08 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0010_booking_approval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='guest',
            new_name='customer',
        ),
    ]
