# Generated by Django 5.0.1 on 2024-02-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0012_customers_image_staff_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='age',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
